### PR TITLE
perf(mlcache) define shm_value types as integers

### PR DESCRIPTION
**Pull request by p0pr0ck5**
Since we can only marshall a defined set of value types, we can
avoid the Lua GC/interning overhead needed to track marshalled
types as an unsigned char*; we can instead associate acceptable
Lua types with an integer, and use a lookup table to build the
shm_value appropriately when marshalling.

### CODE REVIEW

**Comment by thibaultcha** [comment]
Very cool! Thank you! 😄

**Comment by thibaultcha** [comment]
Feels good not to have to write tests for a patch heh?

**Comment by p0pr0ck5** [comment]
So I got lazy and didn't read through all of the `get` tests, and was going to write a separate PR for uncachable types before I saw test 11 ;)

**Comment by thibaultcha** [comment]
Do you want to benchmark this before merging or... nah?

**Comment by p0pr0ck5** [comment]
We can. I think to make it worthwhile we should test against an extensive harness that tests performance against loops with multiple types, conditions, branches, etc. stap is buggered on my box, so I can build and run this in a few days if we want this. Otherwise, unless we're missing something silly, I don't see how this is going to be a hindrance, but I'm not in a hurry to merge. Your call :)

**Comment by thibaultcha** [comment]
> think to make it worthwhile we should test against an extensive harness that tests performance against loops with multiple types, conditions, branches, etc

Read my mind, was just wondering if you wanted to hold on regardless. Alright !

**Comment by p0pr0ck5** [comment]
This will make a good blog post :)

**Comment by thibaultcha** [comment]
Which part?

**Comment by p0pr0ck5** [comment]
The whole thing (performance before and after, JIT-ed changes, etc).

**Comment by thibaultcha** [comment]
:+1:

**Pull request merged**
